tool:
  nodejs:
    installations:
    - name: "NodeJS_9.5.0"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "9.5.0"
              npmPackagesRefreshHours: 72