tool:
  nodejs:
    installations:
    - name: "node"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "9.11.2"
              npmPackagesRefreshHours: 72