jenkins:
  nodes:
  - permanent:
      launcher:
        ssh:
          credentialsId: "ubuntu-user"
          host: "jenkins-mac.zenoh.io"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqB0zAloATU+Sz9m64ljhzzmWzHDLkpBmPTqqgMVG9efT8E7XALe9W9jCqQBVOP3d3njDsM+C+DIWON3d3lwBSkicKT1DaEtDIsJNqCt71qb02oUm2IGL3SA9bqMSnnYUajZFnsB2xGO2WIfw+TNgj0sMpVAyEjTf1D3iM0NS4Ncxj9LvH95dl2KNcGHIqaCngRcryc15DZMJInEzRWhvRXgNJJLQTLEULP92kaJ5Cqm0gblAR20JzAnilpH9Ahv+NrxAR7SEuNl4N0LVD8fnPIWlO8n3pRC7I24HbwoaVdzOikNVLP5ywTjdweZEagAyD4vvwaXr7MBREdQBYBkXhPdMjRypEDhywKbG405mrmU2Ei4FreE/otwgqPjzmP/Pv2dOV7kGebjhql+kT6rqYSmY8GzPuKB7KA5pqRqWuafUaF9ukkVytA8bYzXiCjFhv8n+X+tEW5BmLHLhs+JeI70F3J2vZ6GYhxJr3OS9+1+KS26d6Dwkm7VqZViEr8pM="
      mode: EXCLUSIVE
      name: "MacMini"
      nodeDescription: "hosted at MacStadium, provided by the project"
      numExecutors: 1
      remoteFS: "/Users/genie.zenoh"
      retentionStrategy: "always"
  - permanent:
      launcher:
        ssh:
          credentialsId: "ubuntu-user"
          host: "jenkins.zenoh.io"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCjVf8WuShEHCMb5bv3/ghhQx8xwsMc9eMYNJg5l+Oq2cSwCoWEoN45ZRLN+BO2rPQQykD2/VevEVLtKOdlDWBlhOMjxryvlW+geFNLPvC0tpbx1ExtqsCHhZ5oBbxytwTciw4WNc3NZC7sWtLV0ZIxk4FGusYuB8fZGyvC/hv7Ftxn7B+07zJP7UvDV2n/RIjaMAh91o072gBWD9QCsvnklqA+FZiWRveigNQR5zbGiNlSavqw3+5EjBgUlvxMPDQlBNsG9+8F1XI1q1zkdGEi7hojjBouXohUwWjb72cFPFbbT3xgJi+3PfV1e7Mn1TrOPNx0AY/AhCGnvgKRhN2ZPRUgfUv28CibKR2qhjJbxkPZsqXvq5Ayzy0ANbLCopj1vB14mYTwDqB/MYTkG+15Ar8TDefsTXw9Lc3NaueqvWqa7yP+GP0zihMSupq9nQQLgi5p1PJDRiSRiUJssr2X1n0PYUlW9yCjAMjlADC9PjU2zCEfyw85H3y5vUidAU="
      mode: EXCLUSIVE
      name: "UbuntuVM"
      nodeDescription: "hosted at Linode, provided by the project"
      numExecutors: 1
      remoteFS: "/home/genie.zenoh"
      retentionStrategy: "always"
