jenkins:
  nodes:
  - permanent:
      name: "centslave2"
      nodeDescription: "CentOS"
      labelString: "centos"
      remoteFS: '/home/cbi/genie.platform'
      numExecutors: 2
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "centslave2.eclipse.org"
          port: "22"
          credentialsId: "79afba13-7d0f-45d9-91c1-7009ae7e0d7e"
          javaPath: "/shared/common/jdk1.8.0-latest/bin/java"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa23PeYP41r8dTo5CW5/zls1eg0f9euBTxdmu4Tyf/UmfVV3/1s/gdSm9pm6pJQJiGOgjk9in+KkN5QFX7uTobwedZztWV4YRERQe7pZO4iF7fCbFIEECDTN86ZMlFTwS16kgUTsa6n/5WYiSWYljJF4sZZfDZAkpvvRGwBFuuVA3AKNxkJ9NrPcWF4S8iPeGLe+n4sGpRmE4tEiZCWzhPqhayNQxos3KMmihrGu8wKtqwvWftL/sRzNoXuecqbRcEk6c+Cm3K7rqmPpZ1KJ6bqDPe3YrP1EwrgXujZBT05/GvIhn7OEkpDnCoCK0lb9xH/gG8kkZGbOwAXeeJA47D"
  - permanent:
      name: "hippcentos"
      nodeDescription: "CentOS"
      labelString: "centos"
      remoteFS: '/home/cbi/genie.platform'
      numExecutors: 3
      mode: EXCLUSIVE
      retentionStrategy: "always"
      launcher:
        ssh:
          host: "hippcentos"
          port: "22"
          credentialsId: "79afba13-7d0f-45d9-91c1-7009ae7e0d7e"
          javaPath: "/opt/public/common/jdk1.8.0-latest/bin/java"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDldgJ5lA4pZ3gXQ6CS4b/F5XjT/HqFTRF9Fy4Ozne8BloiIoqTb9PH3Rvvjo2xZAkwFggE+eV0YP/HvrLB9N7HH1UfATencTtFMrSVQgNKkBqzRlghQ41XS+4mDcUenjKJhkhkW1RYRbnEfNGfkRHjY3xLZYAdSxa9dH0H/XNIw+Ge3+w+nb+qqsDgM0234MVJEsDxj8hGnys5QgGL3tGRCcoXP/lIEumad7lh6AjWOpzrsaUGbkwfIjlLJlbj07HfCEQ23rMUIDqSBdShAhY882YfRwR20hIcz9MeFit0KGPOXEju2T7fnKqYzZmR55lTaqd50yT03ljSTcqRYjfp"
      nodeProperties:
      - envVars:
          env:
          - key: "G_FILENAME_ENCODING"
            value: "@locale,UTF-8,ISO-8859-15,CP1252"
          - key: "LANG"
            value: "en_US.UTF-8"
          - key: "LC_ALL"
            value: "en_US.UTF-8"
