jenkins:
  nodes:
  - permanent:
      labelString: ""
      launcher:
        ssh:
          credentialsId: "d483cc19-fc32-42e0-af52-25b4a22d6aa9"
          host: "35.222.20.36"
          jvmOptions: "-Xmx256m -Xms256m"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFfmeEuQxcv8CrnBNFGe470JtdEEtYukrOa7QsBY02GyhCoRYsJwyKA7dGgHm/m6euRJIpMGudwUm3iOpMFazxE="
      mode: EXCLUSIVE
      name: "egerrit-slave"
      nodeDescription: "Google Ubuntu machine where to perform builds and tests"
      remoteFS: "/home/webmaster/egerrit"