jenkins:
  nodes:
  - permanent:
      launcher:
        sSHLauncher:
          credentialsId: "78cd25b2-cbb1-4a7f-8888-5f742271148e"
          host: "centslave1.eclipse.org"
          javaPath: "/shared/common/jdk1.8.0_x64-latest/bin/java"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa23PeYP41r8dTo5CW5/zls1eg0f9euBTxdmu4Tyf/UmfVV3/1s/gdSm9pm6pJQJiGOgjk9in+KkN5QFX7uTobwedZztWV4YRERQe7pZO4iF7fCbFIEECDTN86ZMlFTwS16kgUTsa6n/5WYiSWYljJF4sZZfDZAkpvvRGwBFuuVA3AKNxkJ9NrPcWF4S8iPeGLe+n4sGpRmE4tEiZCWzhPqhayNQxos3KMmihrGu8wKtqwvWftL/sRzNoXuecqbRcEk6c+Cm3K7rqmPpZ1KJ6bqDPe3YrP1EwrgXujZBT05/GvIhn7OEkpDnCoCK0lb9xH/gG8kkZGbOwAXeeJA47D"
      mode: EXCLUSIVE
      name: "centslave1"
      nodeDescription: "CentOS"
      nodeProperties:
      - toolLocation:
          locations:
          - home: "/shared/common/jdk1.8.0_x64-latest"
            key: "hudson.model.JDK$DescriptorImpl@oracle-jdk8-latest"
          - home: "/shared/common/apache-maven-latest"
            key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@apache-maven-latest"
      numExecutors: 1
      remoteFS: "/opt/public/hipp/homes/genie.cbi/centslave1"
  - permanent:
      launcher:
        sSHLauncher:
          credentialsId: "78cd25b2-cbb1-4a7f-8888-5f742271148e"
          host: "mac-tests2"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI1Vs9ZuP6MeO2HbL2se+cXN7/xIQ/08WxTTxKf/6whsaFuFcIEZ7xB1ANeKwLA0mv3HhK43azBIg0Xcwbb9s91wFuiBlASAoLK8NKisyXsoGRjV4ShvzkAWPybQTQi9Z/I5sbMB590qlIu3EIrtRz8O1f0sXMnbZwCm/PMcq72uT5Fykjh7iM1NnEVjfCLECf8cyaHzMWOTkUwjaITuXsaRZHKvzyENejrCOYaO4PMTk0FJfyApB8mzthgtKsfMMrz/ccXNT3o5iC2I3Y1pbsWf1nBkaJD+t1wACkwv0j12BYdlLE6ZEAirvUd2ICy0hgFSyUkxTCW6nT6t+MyTP/"
      mode: EXCLUSIVE
      name: "mac-tests2"
      nodeProperties:
      - envVars:
          env:
          - key: "JAVA_HOME"
            value: "/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home"
      - toolLocation:
          locations:
          - home: "/shared/common/apache-maven-latest"
            key: "hudson.tasks.Maven$MavenInstallation$DescriptorImpl@apache-maven-latest"
          - home: "/usr/bin/git"
            key: "hudson.plugins.git.GitTool$DescriptorImpl@git"
          - home: "/shared/common/apache-ant-1.8.4"
            key: "hudson.tasks.Ant$AntInstallation$DescriptorImpl@apache-ant-latest"
      remoteFS: "/Users/genie.cbi"
  - permanent:
      labelString: "docker-build"
      launcher:
        sSHLauncher:
          credentialsId: "cfaf31c8-22ea-487d-9d6d-b7dd77b624f5"
          host: "13.77.107.72"
          jvmOptions: "-Xmx256m -Xms256m"
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeTB1LA7FnUI8kNrY8zVx/Ywy1RN4tJj11W9QWFWTr6gAJgSNEneKIa8hnjZEPddYOIsBOQ9VSvgXYGFRKEFXW23zskuWEyCqSZ/e7RTw2VTCh5nfUZlX1eG7iujn1mpineX/+hRR7HtxDM9MPhpbrq6HVjXuSx8mex9vu4p20ZVZkewedmtG2+qYDDTsv8uw0kX+kkyRuE6An14omsCQ+8mJ17zQnGXN2CnrXXMOWbgH9BC8RZUvNZOzNY1JkWf9EqY2Tz3YJPgUM+9qVj3/BEjGopEIUT/jDuk2NnOo+V1GT8aWzwmBjv91F7wgjuQ72cV8GeSbxz0utQ9isuMkp"
      mode: EXCLUSIVE
      name: "fmlw3-ubuntu1804"
      nodeDescription: "2vCPU, 8GB RAM, Hosted @ Azure"
      remoteFS: "/home/genie.cbi/jenkins-agent"
