spec:
  template:
    spec:
      containers:
      - name: jenkins
        volumeMounts:
        - mountPath: /var/jenkins_home/.ssh
          name: master-known-hosts
      volumes:
      - name: master-known-hosts
        configMap:
          name: master-known-hosts
          