#*******************************************************************************
# Copyright (c) 2019 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    org.eclipse.cbi.jiro/project.shortname: "platform"
    org.eclipse.cbi.jiro/project.fullName: "eclipse.platform"
    org.eclipse.cbi.jiro/kind: "master"
  annotations:
    org.eclipse.cbi.jiro/jenkins.version: "latest"
    org.eclipse.cbi.jiro/jenkins.actualVersion: "2.176.2"
    org.eclipse.cbi.jiro/kubernetes.master.namespace: "platform"
    org.eclipse.cbi.jiro/project.sponsorshipLevel: "S3"
  namespace: "platform"
  name: jenkins-config
data:
  jenkins.yaml: |
    # GENERATED FILE - DO NOT EDIT
    jenkins:
      agentProtocols:
      - JNLP4-connect
      - Ping
      authorizationStrategy:
        projectMatrix:
          permissions:
          - Overall/Administer:admins
          - Job/Read:anonymous
          - Overall/Read:anonymous
          - Job/ExtendedRead:common
          - Agent/Build:eclipse.platform
          - Credentials/View:eclipse.platform
          - Gerrit/ManualTrigger:eclipse.platform
          - Gerrit/Retrigger:eclipse.platform
          - Job/Build:eclipse.platform
          - Job/Cancel:eclipse.platform
          - Job/Configure:eclipse.platform
          - Job/Create:eclipse.platform
          - Job/Delete:eclipse.platform
          - Job/Move:eclipse.platform
          - Job/Read:eclipse.platform
          - Job/Workspace:eclipse.platform
          - Run/Delete:eclipse.platform
          - Run/Replay:eclipse.platform
          - Run/Update:eclipse.platform
          - SCM/Tag:eclipse.platform
          - View/Configure:eclipse.platform
          - View/Create:eclipse.platform
          - View/Delete:eclipse.platform
          - View/Read:eclipse.platform
      clouds:
      - kubernetes:
          containerCapStr: "8"
          jenkinsTunnel: jenkins-discovery.platform.svc.cluster.local:50000
          jenkinsUrl: http://jenkins-ui.platform.svc.cluster.local/platform
          maxRequestsPerHostStr: "32"
          name: kubernetes
          namespace: platform
          podRetention: never
          templates:
          - containers:
            - args: ""
              command: ""
              image: eclipsecbijenkins/jenkins-agent:3.29@sha256:4929ec01abc1ad507dcdaea823953d71395c8bac67d94d692be266969ce75bfc
              livenessProbe:
                failureThreshold: 0
                initialDelaySeconds: 0
                periodSeconds: 0
                successThreshold: 0
                timeoutSeconds: 0
              name: jnlp
              resourceLimitCpu: 2000m
              resourceLimitMemory: 4096Mi
              resourceRequestCpu: 1000m
              resourceRequestMemory: 4096Mi
              ttyEnabled: true
            envVars:
            - envVar:
                key: MAVEN_OPTS
                value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - envVar:
                key: MAVEN_CONFIG
                value: -B -e
            instanceCap: 5
            name: default-agent
            namespace: platform
            nodeUsageMode: NORMAL
            volumes:
            - persistentVolumeClaim:
                claimName: tools-claim-jiro-platform
                mountPath: /opt/tools
                readOnly: true
            - configMapVolume:
                configMapName: known-hosts
                mountPath: /home/jenkins/.ssh/
            - emptyDirVolume:
                memory: false
                mountPath: /home/jenkins/.m2/repository
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            yaml: |
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: jnlp
                  volumeMounts:
                  - name: settings-xml
                    mountPath: /home/jenkins/.m2/settings.xml
                    subPath: settings.xml
                    readOnly: true
                  - name: toolchains-xml
                    mountPath: /home/jenkins/.m2/toolchains.xml
                    subPath: toolchains.xml
                    readOnly: true
                  - name: settings-security-xml
                    mountPath: /home/jenkins/.m2/settings-security.xml
                    subPath: settings-security.xml
                    readOnly: true
                volumes:
                - name: settings-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings.xml
                      path: settings.xml
                - name: toolchains-xml
                  configMap:
                    name: m2-dir
                    items:
                    - key: toolchains.xml
                      path: toolchains.xml
                - name: settings-security-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings-security.xml
                      path: settings-security.xml
          - containers:
            - args: ""
              command: ""
              image: eclipsecbijenkins/ui-test-agent:3.29@sha256:b5f847bd86f2761b7c8487e8b97fc5925d9aba6382c88a68fea1aaa01e12db59
              livenessProbe:
                failureThreshold: 0
                initialDelaySeconds: 0
                periodSeconds: 0
                successThreshold: 0
                timeoutSeconds: 0
              name: jnlp
              resourceLimitCpu: 2000m
              resourceLimitMemory: 4096Mi
              resourceRequestCpu: 1000m
              resourceRequestMemory: 4096Mi
              ttyEnabled: true
            envVars:
            - envVar:
                key: MAVEN_OPTS
                value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - envVar:
                key: MAVEN_CONFIG
                value: -B -e
            instanceCap: 5
            instanceCapStr: "5"
            label: ui-test
            name: ui-test-agent
            namespace: platform
            volumes:
            - persistentVolumeClaim:
                claimName: tools-claim-jiro-platform
                mountPath: /opt/tools
                readOnly: true
            - configMapVolume:
                configMapName: known-hosts
                mountPath: /home/jenkins/.ssh/
            - emptyDirVolume:
                memory: false
                mountPath: /home/jenkins/.m2/repository
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            yaml: |
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: jnlp
                  volumeMounts:
                  - name: settings-xml
                    mountPath: /home/jenkins/.m2/settings.xml
                    subPath: settings.xml
                    readOnly: true
                  - name: toolchains-xml
                    mountPath: /home/jenkins/.m2/toolchains.xml
                    subPath: toolchains.xml
                    readOnly: true
                  - name: settings-security-xml
                    mountPath: /home/jenkins/.m2/settings-security.xml
                    subPath: settings-security.xml
                    readOnly: true
                volumes:
                - name: settings-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings.xml
                      path: settings.xml
                - name: toolchains-xml
                  configMap:
                    name: m2-dir
                    items:
                    - key: toolchains.xml
                      path: toolchains.xml
                - name: settings-security-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings-security.xml
                      path: settings-security.xml
          - containers:
            - args: ""
              command: ""
              image: eclipsecbijenkins/migration-fat-agent:3.29@sha256:a341be4b6509400aaa18081d86f66239ceb93897059386120ef6633aa378931f
              livenessProbe:
                failureThreshold: 0
                initialDelaySeconds: 0
                periodSeconds: 0
                successThreshold: 0
                timeoutSeconds: 0
              name: jnlp
              resourceLimitCpu: 2000m
              resourceLimitMemory: 4096Mi
              resourceRequestCpu: 1000m
              resourceRequestMemory: 4096Mi
              ttyEnabled: true
            envVars:
            - envVar:
                key: MAVEN_OPTS
                value: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            - envVar:
                key: MAVEN_CONFIG
                value: -B -e
            instanceCap: 5
            instanceCapStr: "5"
            label: migration
            name: migration-agent
            namespace: platform
            volumes:
            - persistentVolumeClaim:
                claimName: tools-claim-jiro-platform
                mountPath: /opt/tools
                readOnly: true
            - configMapVolume:
                configMapName: known-hosts
                mountPath: /home/jenkins/.ssh/
            - emptyDirVolume:
                memory: false
                mountPath: /home/jenkins/.m2/repository
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            yaml: |
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: jnlp
                  volumeMounts:
                  - name: settings-xml
                    mountPath: /home/jenkins/.m2/settings.xml
                    subPath: settings.xml
                    readOnly: true
                  - name: toolchains-xml
                    mountPath: /home/jenkins/.m2/toolchains.xml
                    subPath: toolchains.xml
                    readOnly: true
                  - name: settings-security-xml
                    mountPath: /home/jenkins/.m2/settings-security.xml
                    subPath: settings-security.xml
                    readOnly: true
                volumes:
                - name: settings-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings.xml
                      path: settings.xml
                - name: toolchains-xml
                  configMap:
                    name: m2-dir
                    items:
                    - key: toolchains.xml
                      path: toolchains.xml
                - name: settings-security-xml
                  secret:
                    secretName: m2-secret-dir
                    items:
                    - key: settings-security.xml
                      path: settings-security.xml
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: false
      disableRememberMe: false
      markupFormatter: rawHtml
      mode: EXCLUSIVE
      nodes:
      - permanent:
          labelString: centos
          launcher:
            ssh:
              credentialsId: 79afba13-7d0f-45d9-91c1-7009ae7e0d7e
              host: centslave2.eclipse.org
              javaPath: /shared/common/jdk1.8.0-latest/bin/java
              port: "22"
              sshHostKeyVerificationStrategy:
                manuallyProvidedKeyVerificationStrategy:
                  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDa23PeYP41r8dTo5CW5/zls1eg0f9euBTxdmu4Tyf/UmfVV3/1s/gdSm9pm6pJQJiGOgjk9in+KkN5QFX7uTobwedZztWV4YRERQe7pZO4iF7fCbFIEECDTN86ZMlFTwS16kgUTsa6n/5WYiSWYljJF4sZZfDZAkpvvRGwBFuuVA3AKNxkJ9NrPcWF4S8iPeGLe+n4sGpRmE4tEiZCWzhPqhayNQxos3KMmihrGu8wKtqwvWftL/sRzNoXuecqbRcEk6c+Cm3K7rqmPpZ1KJ6bqDPe3YrP1EwrgXujZBT05/GvIhn7OEkpDnCoCK0lb9xH/gG8kkZGbOwAXeeJA47D
          mode: EXCLUSIVE
          name: centslave2
          nodeDescription: CentOS
          numExecutors: 2
          remoteFS: /home/cbi/genie.platform
          retentionStrategy: always
      - permanent:
          labelString: centos
          launcher:
            ssh:
              credentialsId: 79afba13-7d0f-45d9-91c1-7009ae7e0d7e
              host: hippcentos
              javaPath: /opt/public/common/jdk1.8.0-latest/bin/java
              port: "22"
              sshHostKeyVerificationStrategy:
                manuallyProvidedKeyVerificationStrategy:
                  key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDldgJ5lA4pZ3gXQ6CS4b/F5XjT/HqFTRF9Fy4Ozne8BloiIoqTb9PH3Rvvjo2xZAkwFggE+eV0YP/HvrLB9N7HH1UfATencTtFMrSVQgNKkBqzRlghQ41XS+4mDcUenjKJhkhkW1RYRbnEfNGfkRHjY3xLZYAdSxa9dH0H/XNIw+Ge3+w+nb+qqsDgM0234MVJEsDxj8hGnys5QgGL3tGRCcoXP/lIEumad7lh6AjWOpzrsaUGbkwfIjlLJlbj07HfCEQ23rMUIDqSBdShAhY882YfRwR20hIcz9MeFit0KGPOXEju2T7fnKqYzZmR55lTaqd50yT03ljSTcqRYjfp
          mode: EXCLUSIVE
          name: hippcentos
          nodeDescription: CentOS
          nodeProperties:
          - envVars:
              env:
              - key: G_FILENAME_ENCODING
                value: '@locale,UTF-8,ISO-8859-15,CP1252'
              - key: LANG
                value: en_US.UTF-8
              - key: LC_ALL
                value: en_US.UTF-8
          numExecutors: 3
          remoteFS: /home/cbi/genie.platform
          retentionStrategy: always
      numExecutors: 0
      remotingSecurity:
        enabled: true
      scmCheckoutRetryCount: 2
      securityRealm:
        ldap:
          configurations:
          - displayNameAttributeName: cn
            groupSearchBase: ou=group
            mailAddressAttributeName: mail
            rootDN: dc=eclipse,dc=org
            server: ldapmaster
            userSearch: mail={0}
      systemMessage: ""
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      downloadSettings:
        useBrowser: false
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: triggeringUsersAuthorizationStrategy
      sSHD:
        port: -1
    tool:
      ant:
        installations:
        - home: ""
          name: apache-ant-latest
          properties:
          - installSource:
              installers:
              - antFromApache:
                  id: 1.10.5
      git:
        installations:
        - home: git
          name: Default
      jdk:
        installations:
        - home: /opt/tools/java/openjdk/latest
          name: openjdk-latest
        - home: /opt/tools/java/openjdk/jdk-13ea/latest
          name: openjdk-jdk13ea-latest
        - home: /opt/tools/java/openjdk/jdk-12/latest
          name: openjdk-jdk12-latest
        - home: /opt/tools/java/openjdk/jdk-11/latest
          name: openjdk-jdk11-latest
        - home: /opt/tools/java/openjdk/jdk-10/latest
          name: openjdk-jdk10-latest
        - home: /opt/tools/java/openjdk/jdk-9/latest
          name: openjdk-jdk9-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-latest
          name: adoptopenjdk-hotspot-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-jdk-12/latest
          name: adoptopenjdk-hotspot-jdk12-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-jdk-11/latest
          name: adoptopenjdk-hotspot-jdk11-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-jdk-10/latest
          name: adoptopenjdk-hotspot-jdk10-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-jdk-9/latest
          name: adoptopenjdk-hotspot-jdk9-latest
        - home: /opt/tools/java/adoptopenjdk/hotspot-jdk-8/latest
          name: adoptopenjdk-hotspot-jdk8-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-latest
          name: adoptopenjdk-openj9-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-jdk-12/latest
          name: adoptopenjdk-openj9-jdk12-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-jdk-11/latest
          name: adoptopenjdk-openj9-jdk11-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-jdk-10/latest
          name: adoptopenjdk-openj9-jdk10-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-jdk-9/latest
          name: adoptopenjdk-openj9-jdk9-latest
        - home: /opt/tools/java/adoptopenjdk/openj9-jdk-8/latest
          name: adoptopenjdk-openj9-jdk8-latest
        - home: /opt/tools/java/oracle/latest
          name: oracle-latest
        - home: /opt/tools/java/oracle/jdk-10/latest
          name: oracle-jdk10-latest
        - home: /opt/tools/java/oracle/jdk-9/latest
          name: oracle-jdk9-latest
        - home: /opt/tools/java/oracle/jdk-8/latest
          name: oracle-jdk8-latest
        - home: /opt/tools/java/oracle/jdk-7/latest
          name: oracle-jdk7-latest
        - home: /opt/tools/java/oracle/jdk-6/latest
          name: oracle-jdk6-latest
        - home: /opt/tools/java/oracle/jdk-5/latest
          name: oracle-jdk5-latest
        - home: /opt/tools/java/oracle/jdk-1.4/latest
          name: oracle-jdk1.4-latest
        - home: /opt/tools/java/ibm/jdk-8/latest
          name: ibm-jdk8-latest
        - home: /opt/tools/java/ibm/latest
          name: ibm-latest
      maven:
        installations:
        - home: /opt/tools/apache-maven/latest
          name: apache-maven-latest
        - home: /opt/tools/apache-maven/3.6.1
          name: apache-maven-3.6.1
        - home: /opt/tools/apache-maven/3.5.4
          name: apache-maven-3.5.4
        - home: /opt/tools/apache-maven/3.3.9
          name: apache-maven-3.3.9
        - home: /opt/tools/apache-maven/3.2.5
          name: apache-maven-3.2.5
    unclassified:
      extendedEmailPublisher:
        defaultContentType: text/html
      globalDefaultFlowDurabilityLevel:
        durabilityHint: PERFORMANCE_OPTIMIZED
      location:
        adminAddress: ci-admin@eclipse.org
        url: https://ci-staging.eclipse.org/platform
      mailer:
        adminAddress: ci-admin@eclipse.org
        replyToAddress: ci-admin@eclipse.org
        smtpHost: mail.eclipse.org
      simple-theme-plugin:
        elements:
        - cssUrl:
            url: /platform/userContent/theme/quicksilver.css
        - cssUrl:
            url: //fonts.googleapis.com/css?family=Libre+Franklin:400,700,300,600,100
        - jsUrl:
            url: /platform/userContent/theme/title.js
